[package]
name = "ratatui-widgets"
version = "0.1.0"
authors = ["Joshka"]
description = "A set of widgets for the ratatui terminal UI library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/joshka/ratatui-widgets"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
